application: gdggdl-playground
version: 1
runtime: python27
api_version: 1

threadsafe: true

handlers:
# Script handlers
- url: .*
  script: main.application

- url: /index\.html
  script: main.application

# Static handlers
- url: /stylesheets
  static_dir: static/stylesheets

- url: /(favicon\.ico|robots\.txt)
  static_files: static/\1
  upload: static/(favicon\.ico|robots\.txt)

libraries:
- name: webapp2
  version: "latest" # 2.5.2