application: gdggdl-playground
version: 1
runtime: python27
api_version: 1

threadsafe: true

handlers:
# Static handlers
- url: /stylesheets
  static_dir: static/stylesheets

- url: /(robots\.txt|favicon\.ico)
  static_files: static/\1
  upload: static/(robots\.txt|favicon\.ico)

# Script handlers
- url: .*
  script: main.application

- url: /index\.html
  script: main.application


libraries:
# Third party libraries: https://developers.google.com/appengine/docs/python/tools/libraries27
- name: webapp2
  version: "latest" # 2.5.2
- name: jinja2
  version: "latest" # 2.6